version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: snippet
      POSTGRES_PASSWORD: snippet
      POSTGRES_DB: snippet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ../.env.example
    environment:
      - DATABASE_URL=postgresql://snippet:snippet@db:5432/snippet
      - REDIS_URL=redis://redis:6379
      - SITE_URL=http://localhost:4000
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  pgdata:
